name: Testsuite

on:
  pull_request:
  push:
    branches:
      - main
      - ci-debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: svg
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync
      - name: Unit tests
        run: |
          uv run coverage run -m pytest
          output=$(uv run coverage report -m)
          exit_code_coverage=$?
          if [ $exit_code_coverage -eq 0 ]; then
            echo ":white_check_mark: Test Coverage" >> $GITHUB_STEP_SUMMARY
          else
            echo ":x: Test Coverage" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Test Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '<pre>' >> $GITHUB_STEP_SUMMARY
          echo "$output" | head -n 100 >> $GITHUB_STEP_SUMMARY
          echo '</pre>' >> $GITHUB_STEP_SUMMARY
          if [ $exit_code_tests -ne 0 ] || [ $exit_code_coverage -ne 0 ]; then
            exit 1
          fi
